sequenceDiagram
    box
        participant start
        participant Agent
        participant Shopper
    end
    box rgb(27, 119, 219) Pre-Purchase
        participant GABI UI
        participant Purchase App
        participant GABI API
    end
    box green Post-Purchase DCT
        participant DCT
    end
    box rgb(0, 82, 204) Post-Purchase Jira Automation
        participant Jira
        end
    box Post-Purchase APIs
        participant Gateway
        participant PWS API
        participant WDO API
    end
    box Purple Post-Purchase WOS Automation
        participant Chatterbox
        participant WOS
    end
    
    start->>Agent: Agent and customer enter a call
    activate Agent
    Agent ->>+ GABI UI: Agent Opens GABI UI from CRM
    GABI UI ->>+ GABI API: Agent submits DIFY lead data
    GABI API->GABI UI:  
    GABI UI->>Agent: 
    Agent->>Purchase App: Agent Completes Purchase of WDS product
    Purchase App->>Agent: 
    Agent->>start: 
    deactivate Agent
    note right of Jira: async event ADD_ACCOUNT sent to MSH lambda
    start->>Jira: Jira ticket created for website build
    start->>Agent: 
    activate Agent
    Agent-->>DCT: Agent opens DCT
    note over Agent,DCT: Optional step
    DCT-->>GABI API: GET /v1/sales-call-info
    GABI API-->>DCT: 
    DCT-->>DCT: inject GABI lead data into DCT
    DCT-->>DCT: Agent clicks continue
    DCT-->>Jira: Add Jira label dct-ai-content
    Jira-->>DCT: 
    loop Agent and Customer edit DCT
    DCT-->>PWS API: PUT /v3/design-consultation 
    PWS API-->>DCT: 
    end
    DCT-->>PWS API: Submit DCT form
    PWS API-->>+Jira: Transition ticket to Setup for Build
    Jira-->>-PWS API: 
    PWS API-->>DCT: 
    DCT-->>Agent:      
    Agent->>start: Agent and customer end the call
    deactivate Agent
    start-->>+Jira: Jira automation
    note over start, Jira: If DCT was not submitted (never opened or in progress)
    Jira-->>-Jira: Transition the ticket to Setup for Build after 24 hours after ticket creation
    Jira->>Gateway: Setup for Build status transition webhook
    Gateway->>Jira: 
    Gateway->>Chatterbox: Send AUTOMATE_CONTENT_GENERATION event
    Chatterbox->>Gateway: 
    Chatterbox->>WOS: Process AUTOMATE_CONTENT_GENERATION event
    WOS->>PWS API: GET /v3/design-consultation
    PWS API->>WOS: 
    WOS->>WDO API: POST /v1/validate-business-profile with business profile data
    WDO API->>WOS: 
    WOS-->>WOS: if business profile is complete, skip to next step
    WOS->>WDO API: if business profile is incomplete, POST /v1/instant-onboard
    WDO API->>WOS: 
    WOS->>WOS: merge result of /v3/design-consultation and /v1/instant-onboard
    WOS->>PWS API: save merged result
    PWS API->>WOS: 
    WOS->>WOS: Continue Site Automation...
    
    
    
